### ISSUE TITLE
Crash during cancel

### ISSUE THREAD

**Issue by EXperementatorAV** [qoala101/esc#2] opened 2023-06-30 06:20 UTC
When I selected the type of node with the slider and clicked cancel, the program crashed, now there is no way to try again, but if the problem does not repeat, then I will try to repeat it myself and describe it more accurately

**Comment by qoala101** [comment] 2023-06-30 10:05
Couldn't reproduce it myself, but noticed possible source of the issue in code. Will be fixed in next release.
Thanks!

**Closed as completed** 2023-07-06 07:14 UTC
